"use client";

import { useEffect, useMemo, useState } from "react";

type View = "biblioteca" | "comunidad" | "foro" | "subir" | "lector";
type Book = { id:number; title:string; author:string; year:number; pages:number; type:string; color:string; cover:string; synopsis:string; rating:number; available:number; copies:number; readers:string[]; progress?:number };

const books: Book[] = [
  {id:1,title:"El jardín secreto",author:"Frances Hodgson Burnett",year:1911,pages:368,type:"Novela",color:"#b63d2f",cover:"linear-gradient(145deg,#274b3d,#6f9b6b)",synopsis:"Una casa enorme, un jardín cerrado y dos niños que aprenden que cuidar algo también puede transformarlos.",rating:4.8,available:1,copies:1,readers:["Elena","Mateo","Sofía"]},
  {id:2,title:"El principito",author:"Antoine de Saint-Exupéry",year:1943,pages:96,type:"Cuento",color:"#e4ad3b",cover:"linear-gradient(145deg,#12354b,#2d7794)",synopsis:"Un pequeño viajero recorre planetas y descubre, entre encuentros inolvidables, aquello que de verdad importa.",rating:4.9,available:0,copies:1,readers:["Julia","Leo","Mara"]},
  {id:3,title:"Momo",author:"Michael Ende",year:1973,pages:304,type:"Novela",color:"#2d7c73",cover:"linear-gradient(145deg,#7c2636,#d35b4d)",synopsis:"Momo sabe escuchar como nadie. Cuando los hombres grises roban el tiempo, esa sencilla virtud se vuelve extraordinaria.",rating:4.7,available:1,copies:2,readers:["Noa","Elena"]},
  {id:4,title:"National Geographic Kids",author:"Varios autores",year:2024,pages:48,type:"Revista",color:"#d2823b",cover:"linear-gradient(145deg,#123f36,#d3a83d)",synopsis:"Curiosidades sobre animales, naturaleza y ciencia para lectores con muchas preguntas.",rating:4.5,available:2,copies:2,readers:["Mateo"]},
  {id:5,title:"Matilda",author:"Roald Dahl",year:1988,pages:240,type:"Novela",color:"#745a9c",cover:"linear-gradient(145deg,#493362,#b45e75)",synopsis:"Una lectora brillante descubre que su inteligencia y su valentía pueden cambiar las reglas del mundo adulto.",rating:4.8,available:1,copies:1,readers:["Sofía","Julia"]},
  {id:6,title:"Donde viven los monstruos",author:"Maurice Sendak",year:1963,pages:48,type:"Álbum ilustrado",color:"#3a8d63",cover:"linear-gradient(145deg,#213644,#cf8c3c)",synopsis:"Max navega hasta la tierra de los monstruos y descubre que siempre hay un lugar que lo espera.",rating:4.9,available:1,copies:1,readers:["Leo","Noa"]},
  {id:7,title:"Cuentos de buenas noches",author:"Elena Favilli",year:2016,pages:224,type:"Biografía",color:"#c95064",cover:"linear-gradient(145deg,#8a305f,#e69158)",synopsis:"Cien historias breves de mujeres que convirtieron su curiosidad en caminos nuevos.",rating:4.6,available:1,copies:1,readers:["Mara"]},
  {id:8,title:"La historia interminable",author:"Michael Ende",year:1979,pages:496,type:"Novela",color:"#315f86",cover:"linear-gradient(145deg,#3b214e,#b37838)",synopsis:"Un libro misterioso invita a Bastián a entrar en Fantasía y a descubrir su propia voz.",rating:4.9,available:1,copies:1,readers:["Elena","Mateo"]},
  {id:9,title:"Pequeña & Grande: Frida",author:"María Isabel Sánchez",year:2015,pages:32,type:"Biografía",color:"#d36b35",cover:"linear-gradient(145deg,#245f57,#d74d58)",synopsis:"Una introducción luminosa a la vida y la imaginación de Frida Kahlo.",rating:4.4,available:1,copies:1,readers:["Sofía"]},
  {id:10,title:"Atlas de aventuras",author:"Rachel Williams",year:2014,pages:96,type:"Atlas",color:"#7e9445",cover:"linear-gradient(145deg,#213e55,#699c79)",synopsis:"Mapas ilustrados, rutas y maravillas para recorrer el planeta sin salir de casa.",rating:4.7,available:0,copies:1,readers:["Noa","Julia"]},
  {id:11,title:"El árbol generoso",author:"Shel Silverstein",year:1964,pages:64,type:"Álbum ilustrado",color:"#a85135",cover:"linear-gradient(145deg,#214638,#b9a256)",synopsis:"Una historia sencilla sobre el paso del tiempo, el afecto y la generosidad.",rating:4.5,available:1,copies:1,readers:["Mara","Leo"]},
  {id:12,title:"Cosmos para curiosos",author:"Carlotta James",year:2023,pages:152,type:"Divulgación",color:"#6f53a2",cover:"linear-gradient(145deg,#161c44,#855ab2)",synopsis:"Estrellas, planetas y grandes preguntas explicadas para exploradores del universo.",rating:4.6,available:1,copies:1,readers:["Mateo"]},
];

const people = [
  {name:"Elena",pages:3240,now:"El jardín secreto",emoji:"🌿",color:"#e8af78"},{name:"Mateo",pages:2984,now:"Cosmos para curiosos",emoji:"🪐",color:"#82a9c9"},{name:"Sofía",pages:2710,now:"Matilda",emoji:"✨",color:"#c99bc4"},{name:"Noa",pages:2488,now:"Atlas de aventuras",emoji:"🧭",color:"#8db7a0"},{name:"Julia",pages:2195,now:"El principito",emoji:"🌙",color:"#d3a365"},{name:"Leo",pages:1980,now:"Donde viven los monstruos",emoji:"👑",color:"#90a8d0"},{name:"Mara",pages:1832,now:"Cuentos de buenas noches",emoji:"🌸",color:"#d99191"},
];
const initialPosts=[
  {id:1,user:"Elena",book:"El jardín secreto",time:"Hace 12 min",text:"Tal vez un jardín no se abre con una llave, sino cuando alguien decide cuidarlo. Me gustó pensar que Mary florece al mismo ritmo que las plantas.",likes:18,replies:4,color:"#e8af78"},
  {id:2,user:"Mateo",book:"Cosmos para curiosos",time:"Hace 1 h",text:"La luz de algunas estrellas empezó su viaje antes de que naciéramos. Leerlo cambia un poco la forma de mirar la noche.",likes:12,replies:2,color:"#82a9c9"},
  {id:3,user:"Sofía",book:"Matilda",time:"Ayer",text:"Lo más poderoso de Matilda no es mover objetos: es conservar su curiosidad aunque nadie alrededor la comprenda.",likes:27,replies:7,color:"#c99bc4"},
];

type ReactionTargetType = "post" | "profile";
const reactionKey=(targetType:ReactionTargetType,targetId:string|number,emoji:string)=>`${targetType}:${String(targetId)}:${emoji}`;

function Avatar({name,color,small=false}:{name:string;color:string;small?:boolean}){return <div className={`avatar ${small?"small":""}`} style={{background:color}} aria-label={name}>{name[0]}</div>}
function Stars({rating,onSelect}:{rating:number;onSelect?:(rating:number)=>void}){return <span className={`stars ${onSelect?"interactive":""}`} aria-label={`${rating} de 5`}>{[1,2,3,4,5].map(n=>onSelect?<button type="button" key={n} className={n<=rating?"on":""} onClick={()=>onSelect(n)} aria-label={`${n} estrellas`}>★</button>:<span key={n} className={n<=Math.round(rating)?"on":""}>★</span>)}</span>}

export default function Home(){
  const [view,setView]=useState<View>("biblioteca"),[selected,setSelected]=useState<Book>(books[0]),[search,setSearch]=useState(""),[year,setYear]=useState(""),[type,setType]=useState("");
  const readBooks=[books[0],books[2],books[4],books[5]];
  const [owned,setOwned]=useState<Book|null>({...books[1],progress:36}),[toast,setToast]=useState(""),[modal,setModal]=useState<"detail"|"return"|"profile"|null>(null),[posts,setPosts]=useState(initialPosts),[draft,setDraft]=useState(""),[publishing,setPublishing]=useState(false),[postBook,setPostBook]=useState(readBooks[0].title),[liked,setLiked]=useState<number[]>([]),[reactionCounts,setReactionCounts]=useState<Record<string,number>>({}),[reactionBusy,setReactionBusy]=useState<string[]>([]);
  const [repliesOpen,setRepliesOpen]=useState<number|null>(null),[replyDrafts,setReplyDrafts]=useState<Record<number,string>>({}),[profileReactions,setProfileReactions]=useState<string[]>([]),[returnRating,setReturnRating]=useState(0),[fileInfo,setFileInfo]=useState(""),[bookText,setBookText]=useState("");
  const [loggedIn,setLoggedIn]=useState(true),[authView,setAuthView]=useState<"login"|"signup"|"recover"|null>(null),[recoverySent,setRecoverySent]=useState(false);
  const [shelfPage,setShelfPage]=useState(0);
  const sortedBooks=useMemo(()=>[...books].sort((a,b)=>a.title.localeCompare(b.title,"es",{sensitivity:"base"})),[]);
  const filtered=useMemo(()=>sortedBooks.filter(b=>(!search||`${b.title} ${b.author}`.toLowerCase().includes(search.toLowerCase()))&&(!year||String(b.year)===year)&&(!type||b.type===type)),[search,year,type,sortedBooks]);
  const shelfSize=12,shelfCount=Math.max(1,Math.ceil(sortedBooks.length/shelfSize)),visibleBooks=sortedBooks.slice(shelfPage*shelfSize,(shelfPage+1)*shelfSize);
  const flash=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),2600)};
  useEffect(()=>{
    let cancelled=false;
    fetch("/api/posts")
      .then(async response=>{
        const payload=await response.json();
        if(!response.ok)throw new Error(payload.error||"No se pudo cargar el foro");
        return payload;
      })
      .then(payload=>{
        if(!cancelled&&Array.isArray(payload.posts)){
          setPosts([...payload.posts,...initialPosts]);
        }
      })
      .catch(error=>{
        console.error("No se pudieron cargar las publicaciones persistidas",error);
      });
    return ()=>{cancelled=true};
  },[]);
  useEffect(()=>{
    let cancelled=false;
    fetch("/api/reactions")
      .then(async response=>{
        const payload=await response.json();
        if(!response.ok)throw new Error(payload.error||"No se pudieron cargar las reacciones");
        return payload;
      })
      .then(payload=>{
        if(cancelled)return;
        setReactionCounts(payload.counts&&typeof payload.counts==="object"?payload.counts:{});
        const mine=Array.isArray(payload.mine)?payload.mine:[];
        setLiked(mine.filter((item:{targetType:string;targetId:string;emoji:string})=>item.targetType==="post"&&item.emoji==="❤️").map((item:{targetId:string})=>Number(item.targetId)).filter((id:number)=>Number.isFinite(id)));
        setProfileReactions(mine.filter((item:{targetType:string})=>item.targetType==="profile").map((item:{targetId:string;emoji:string})=>`${item.targetId}-${item.emoji}`));
      })
      .catch(error=>{
        console.error("No se pudieron cargar las reacciones persistidas",error);
      });
    return ()=>{cancelled=true};
  },[]);
  const toggleReaction=async(targetType:ReactionTargetType,targetId:string|number,emoji:string)=>{
    const busyKey=reactionKey(targetType,targetId,emoji);
    if(reactionBusy.includes(busyKey))return null;
    setReactionBusy(current=>[...current,busyKey]);
    try{
      const response=await fetch("/api/reactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetType,targetId:String(targetId),emoji})});
      const payload=await response.json();
      if(!response.ok)throw new Error(payload.error||"No se pudo guardar la reacción");
      setReactionCounts(current=>({...current,[busyKey]:Number(payload.count)||0}));
      if(targetType==="post"){
        const postId=Number(targetId);
        setLiked(current=>payload.active?(current.includes(postId)?current:[...current,postId]):current.filter(id=>id!==postId));
      }else{
        const profileKey=`${String(targetId)}-${emoji}`;
        setProfileReactions(current=>payload.active?(current.includes(profileKey)?current:[...current,profileKey]):current.filter(item=>item!==profileKey));
      }
      return Boolean(payload.active);
    }catch(error){
      flash(error instanceof Error?`No se pudo guardar la reacción: ${error.message}`:"No se pudo guardar la reacción.");
      return null;
    }finally{
      setReactionBusy(current=>current.filter(item=>item!==busyKey));
    }
  };
  const takeBook=()=>{if(selected.available<1){flash("Ese ejemplar está en préstamo. Te avisaremos cuando vuelva.");return}if(owned){flash("Devuelve tu lectura actual antes de tomar otra.");return}setOwned({...selected,progress:0});setModal(null);flash(`“${selected.title}” ya está en tu poder.`)};
  const publish=async()=>{const text=draft.trim();if(!text||publishing)return;setPublishing(true);try{const response=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,book:postBook})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"No se pudo guardar la publicación");setPosts(current=>[payload.post,...current]);setDraft("");flash("Tu reflexión ya está en la conversación.")}catch(error){flash(error instanceof Error?`No se pudo publicar: ${error.message}`:"No se pudo publicar la reflexión.")}finally{setPublishing(false)}};
  const submitReply=(postId:number)=>{if(!replyDrafts[postId]?.trim())return;setPosts(current=>current.map(post=>post.id===postId?{...post,replies:post.replies+1}:post));setReplyDrafts(current=>({...current,[postId]:""}));flash("Respuesta publicada")};
  const toggleProfileReaction=async(name:string,emoji:string)=>{const active=await toggleReaction("profile",name,emoji);if(active!==null)flash(active?`Reaccionaste al perfil de ${name}`:`Quitaste tu reacción a ${name}`)};
  const handleBookFile=async(file?:File)=>{if(!file)return;setFileInfo("Convirtiendo el archivo a texto…");try{let text="";if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")){const [pdfjs,workerModule]=await Promise.all([import("pdfjs-dist"),import("pdfjs-dist/build/pdf.worker.min.mjs?url")]);pdfjs.GlobalWorkerOptions.workerSrc=workerModule.default;const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const pages:string[]=[];for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber);const content=await page.getTextContent();pages.push(content.items.map(item=>("str" in item?item.str:"")).join(" "))}text=pages.join("\n\n")}else{text=await file.text()}setBookText(text);setFileInfo(`${file.name}: ${text.length.toLocaleString("es-MX")} caracteres listos para el visor. El archivo original no se conservará.`)}catch{setBookText("");setFileInfo("No pudimos extraer el texto. Prueba con un PDF con texto seleccionable o un archivo TXT.")}};
  const completeAuth=(message:string)=>{setLoggedIn(true);setAuthView(null);setRecoverySent(false);flash(message)};
  return <main>
    <header className="topbar"><button className="brand" onClick={()=>setView("biblioteca")}><span className="brandmark">B</span><span><b>Biblioteca virtual MJVC Mérida</b><small>Colección, préstamo y lectura en un solo lugar</small></span></button><nav>{[["biblioteca","Estantería"],["comunidad","Lectores"],["foro","Foro"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id as View)}>{label}</button>)}</nav><div className="profile-menu">{loggedIn?<><button className="upload-link" onClick={()=>setView("subir")}>＋ Subir libro</button><button className="me" onClick={()=>setModal("profile")}><Avatar name="Amelia" color="#cf915f" small/><span>Amelia</span></button><button className="logout" onClick={()=>{setLoggedIn(false);setView("biblioteca");flash("Sesión cerrada")}}>Cerrar sesión</button></>:<><button className="login-link" onClick={()=>setAuthView("login")}>Iniciar sesión</button><button className="upload-link" onClick={()=>setAuthView("signup")}>Registrarse</button></>}</div></header>

    {view==="biblioteca"&&<div className="library-layout">
      <aside className="left-panel"><p className="eyebrow">EN TU MESITA</p><h2>{owned?"Una historia te espera":"Tu mesita está libre"}</h2>{owned?<><button className="owned-cover" style={{background:owned.cover}} onClick={()=>setView("lector")}><span>{owned.title}</span><small>{owned.author}</small><i>{owned.progress||36}%</i></button><div className="progress"><span style={{width:`${owned.progress||36}%`}}/></div><p className="muted">Página {Math.round(owned.pages*(owned.progress||36)/100)} de {owned.pages}</p><div className="pair"><button className="primary" onClick={()=>setView("lector")}>Continuar</button><button className="secondary" onClick={()=>setModal("return")}>Devolver</button></div></>:<p className="empty-note">Explora el estante y elige tu próxima lectura.</p>}<div className="leader-mini"><div className="section-title"><div><p className="eyebrow">ZONA DE LECTORES</p><h3>Quienes más han leído</h3></div><button onClick={()=>setView("comunidad")}>Ver todos →</button></div><div className="avatar-row">{people.map((p,i)=><button key={p.name} onClick={()=>setView("comunidad")}><span className="rank">{i+1}</span><Avatar name={p.name} color={p.color} small/></button>)}</div></div><button className="forum-card" onClick={()=>setView("foro")}><span>Conversaciones del club</span><b>Entrar al foro <i>↗</i></b></button></aside>
      <section className="shelf-area"><div className="welcome"><div><p className="eyebrow">{loggedIn?"HOLA, AMELIA":"CATÁLOGO MJVC MÉRIDA"}</p><h1>¿Qué historia te llama hoy?</h1></div><p>{filtered.length} títulos en el estante</p></div><div className="filters"><label className="search"><span>⌕</span><input value={search} onChange={e=>{setSearch(e.target.value);setShelfPage(0)}} placeholder="Busca por título o autor"/></label><label><span>Año</span><select value={year} onChange={e=>{setYear(e.target.value);setShelfPage(0)}}><option value="">Todos</option>{[...new Set(books.map(b=>b.year))].sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}</select></label><label><span>Tipo</span><select value={type} onChange={e=>{setType(e.target.value);setShelfPage(0)}}><option value="">Todos</option>{[...new Set(books.map(b=>b.type))].map(t=><option key={t}>{t}</option>)}</select></label>{(search||year||type)&&<button className="clear" onClick={()=>{setSearch("");setYear("");setType("");setShelfPage(0)}}>Limpiar</button>}</div><div className="shelf-card"><div className="shelf-head"><span>COLECCIÓN GENERAL · A–Z</span><span>Estante {shelfPage+1} de {shelfCount}</span></div><div className="books">{visibleBooks.map(book=>{const match=filtered.includes(book),width=Math.max(36,Math.min(72,30+book.pages/12)),titleSize=Math.round(Math.max(8,Math.min(15,width/(Math.sqrt(book.title.length)*1.45)))*10)/10;return <button key={book.id} className={`book ${match?"match":"dim"} ${book.available<1?"borrowed":""}`} style={{width,background:book.color}} onMouseEnter={()=>setSelected(book)} onClick={()=>{setSelected(book);setModal("detail")}}><span style={{fontSize:titleSize}}>{book.title}</span><small>{book.author.split(" ").slice(-1)}</small>{book.available<1&&<i>•</i>}<div className="hover-cover" style={{background:book.cover}}><b>{book.title}</b><small>{book.author}</small></div></button>})}</div><div className="wood"/></div><div className="shelf-pagination" aria-label="Cambiar de estante"><button disabled={shelfPage===0} onClick={()=>setShelfPage(page=>Math.max(0,page-1))} aria-label="Estante anterior">←</button><span>{shelfPage+1} / {shelfCount}</span><button disabled={shelfPage>=shelfCount-1} onClick={()=>setShelfPage(page=>Math.min(shelfCount-1,page+1))} aria-label="Estante siguiente">→</button></div></section>
      <aside className="right-panel"><p className="eyebrow">LIBRO SELECCIONADO</p><div className="mini-cover" style={{background:selected.cover}}><span>{selected.title}</span></div><p className={`status ${selected.available?"yes":"no"}`}>{selected.available?`${selected.available} ${selected.available===1?"ejemplar disponible":"ejemplares disponibles"}`:"En préstamo"}</p><h2>{selected.title}</h2><p>{selected.author} · {selected.year}</p><div className="rating"><Stars rating={selected.rating}/><b>{selected.rating}</b></div><p className="synopsis">{selected.synopsis}</p><div className="facts"><span><b>{selected.pages}</b> páginas</span><span><b>{selected.type}</b> tipo</span></div><button className="primary wide" onClick={takeBook} disabled={!selected.available}>{selected.available?"Tomar este libro":"No disponible"}</button><div className="readers"><p>Ya lo leyeron</p><div>{selected.readers.map(r=><Avatar key={r} name={r} color={people.find(p=>p.name===r)?.color||"#aaa"} small/>)}<span>+{Math.max(3,selected.readers.length*2)}</span></div></div></aside>
    </div>}

    {view==="comunidad"&&<section className="page community"><div className="page-heading"><p className="eyebrow">ZONA DE LECTORES</p><h1>Una comunidad entre páginas</h1><p>Descubre qué se está leyendo ahora, celebra el avance de otros lectores y encuentra tu próxima conversación.</p></div><div className="pulse"><span className="live-dot"/><b>7 lectores activos ahora</b><span>·</span><span>1,284 páginas leídas esta semana</span></div><div className="people-grid">{people.map((p,i)=><article key={p.name} className="person"><div className="person-top"><span className="place">#{i+1}</span><span>{p.emoji}</span></div><Avatar name={p.name} color={p.color}/><h3>{p.name}</h3><p><b>{p.pages.toLocaleString("es-MX")}</b> páginas leídas</p><div className="reading-now"><span style={{background:books.find(b=>b.title===p.now)?.cover}}/><div><small>LEYENDO AHORA</small><b>{p.now}</b></div></div><div className="reactions">{[["❤️",12],["✨",8],["📚",5]].map(([emoji,count])=>{const emojiValue=String(emoji),key=`${p.name}-${emojiValue}`,active=profileReactions.includes(key),persisted=reactionCounts[reactionKey("profile",p.name,emojiValue)]||0,busy=reactionBusy.includes(reactionKey("profile",p.name,emojiValue));return <button key={key} className={active?"active":""} aria-pressed={active} disabled={busy} onClick={()=>toggleProfileReaction(p.name,emojiValue)}>{emojiValue} {Number(count)+persisted}</button>})}</div></article>)}</div></section>}

    {view==="foro"&&<section className="page forum"><div className="forum-hero"><div><p className="eyebrow">EL FORO</p><h1>Ideas que siguen creciendo</h1><p>Publica reflexiones sobre los libros de tu historial y participa en cualquier conversación.</p></div><button className="primary" onClick={()=>document.getElementById("composer")?.focus()}>Escribir una reflexión</button></div><div className="forum-layout"><div className="feed"><div className="composer"><Avatar name="Amelia" color="#cf915f"/><div className="composer-body"><textarea id="composer" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="¿Qué idea se quedó contigo después de leer?"/><div><select value={postBook} onChange={e=>setPostBook(e.target.value)} aria-label="Libro leído relacionado">{readBooks.map(b=><option key={b.id}>{b.title}</option>)}</select><small className="history-note">Solo libros de tu historial</small><button className="primary" onClick={publish} disabled={publishing}>{publishing?"Publicando…":"Publicar"}</button></div></div></div>{posts.map(post=><article className="post" key={post.id}><div className="post-author"><Avatar name={post.user} color={post.color}/><div><b>{post.user}</b><span>sobre <strong>{post.book}</strong></span></div><time>{post.time}</time></div><p>{post.text}</p><div className="post-actions"><button aria-pressed={liked.includes(post.id)} className={liked.includes(post.id)?"liked":""} disabled={reactionBusy.includes(reactionKey("post",post.id,"❤️"))} onClick={()=>toggleReaction("post",post.id,"❤️")}>{liked.includes(post.id)?"♥":"♡"} {post.likes+(reactionCounts[reactionKey("post",post.id,"❤️")]||0)}</button><button onClick={()=>setRepliesOpen(repliesOpen===post.id?null:post.id)}>↩ {post.replies} respuestas</button><button onClick={()=>flash("Enlace copiado")}>↗ Compartir</button></div>{repliesOpen===post.id&&<div className="reply-box"><Avatar name="Amelia" color="#cf915f" small/><input value={replyDrafts[post.id]||""} onChange={e=>setReplyDrafts(current=>({...current,[post.id]:e.target.value}))} onKeyDown={e=>{if(e.key==="Enter")submitReply(post.id)}} placeholder={`Responder a ${post.user}…`}/><button onClick={()=>submitReply(post.id)}>Responder</button></div>}</article>)}</div><aside className="forum-side"><h3>Lecturas que conversamos</h3>{books.slice(0,4).map((b,i)=><button key={b.id} onClick={()=>{setSelected(b);setView("biblioteca")}}><span style={{background:b.cover}}/><div><b>{b.title}</b><small>{18-i*3} reflexiones</small></div></button>)}<div className="prompt-card"><span>Pregunta de la semana</span><p>¿Qué personaje te enseñó algo sobre ti?</p><button onClick={()=>document.getElementById("composer")?.focus()}>Responder en el foro →</button></div></aside></div></section>}

    {view==="subir"&&<section className="page upload-page"><button className="back" onClick={()=>setView("biblioteca")}>← Volver al estante</button><div className="upload-wrap"><div className="upload-copy"><p className="eyebrow">SUMAR A LA COLECCIÓN</p><h1>Todo libro nuevo abre una puerta</h1><p>Sube el archivo completo. Extraeremos su texto para el visor y descartaremos el archivo original al terminar.</p><blockquote>“Una biblioteca no se hace; crece.”<span>— Augustine Birrell</span></blockquote></div><form className="book-form" onSubmit={e=>{e.preventDefault();if(!bookText){flash("Primero sube un archivo que podamos convertir a texto");return}flash("Libro convertido y enviado para revisión");setTimeout(()=>setView("biblioteca"),900)}}><div className="drop"><span>＋</span><b>Archivo completo del libro</b><small>PDF con texto seleccionable o TXT · máximo 25 MB</small><input required type="file" accept=".pdf,.txt,text/plain,application/pdf" aria-label="Archivo del libro" onChange={e=>handleBookFile(e.target.files?.[0])}/>{fileInfo&&<em className={bookText?"file-ready":"file-error"}>{fileInfo}</em>}</div><div className="field full"><label>Título</label><input required placeholder="Ej. El jardín secreto"/></div><div className="field"><label>Autor</label><input required placeholder="Nombre del autor"/></div><div className="field"><label>Año</label><input required type="number" placeholder="2024"/></div><div className="field"><label>Número de páginas</label><input required type="number" placeholder="120"/></div><div className="field"><label>Tipo</label><select required><option>Libro</option><option>Revista</option><option>Álbum ilustrado</option><option>Biografía</option><option>Otro</option></select></div><div className="field"><label>Ejemplares disponibles</label><input required type="number" defaultValue="1" min="1"/></div><div className="field full"><label>Sinopsis</label><textarea required placeholder="Cuéntanos de qué trata, sin revelar demasiado…"/></div><button className="primary submit">Convertir y enviar a la biblioteca</button></form></div></section>}

    {view==="lector"&&owned&&<section className="reader"><div className="reader-bar"><button onClick={()=>setView("biblioteca")}>← Cerrar lector</button><div><b>{owned.title}</b><span>{owned.author}</span></div><button onClick={()=>flash("Marcador guardado")}>🔖</button></div><div className="reader-page"><span className="chapter">CAPÍTULO 3</span><h1>La puerta escondida</h1><p className="dropcap">A</p><p>quella mañana el aire olía a tierra húmeda. Había llovido durante la noche y cada hoja sostenía una gota brillante, como si el jardín hubiera decidido guardar pequeños espejos.</p><p>Avanzó despacio por el sendero. Sabía que los lugares secretos no se encuentran con prisa: aparecen cuando uno aprende a mirar lo que los demás pasan por alto.</p><p>Al fondo, detrás de la hiedra, algo metálico reflejó la luz. Extendió la mano y apartó las ramas con cuidado.</p><blockquote>Entonces comprendió que algunas puertas no protegen lo que esconden; esperan a la persona correcta.</blockquote></div><div className="reader-controls"><button>‹</button><div><input type="range" min="1" max={owned.pages} defaultValue={Math.round(owned.pages*.36)}/><span>Página {Math.round(owned.pages*.36)} de {owned.pages}</span></div><button>›</button></div></section>}

    {modal==="detail"&&<div className="modal-back" onClick={()=>setModal(null)}><div className="book-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}>×</button><div className="modal-cover" style={{background:selected.cover}}><span>{selected.title}</span><small>{selected.author}</small></div><div className="modal-copy"><p className="eyebrow">{selected.type.toUpperCase()}</p><h2>{selected.title}</h2><p className="by">{selected.author} · {selected.year}</p><div className="rating"><Stars rating={selected.rating}/><b>{selected.rating}</b><span>({selected.readers.length*8+7} lecturas)</span></div><p>{selected.synopsis}</p><div className="meta-row"><span><b>{selected.pages}</b> páginas</span><span><b>{selected.available}/{selected.copies}</b> disponibles</span></div><button className="primary wide" disabled={!selected.available} onClick={takeBook}>{selected.available?"Tomar este libro":"En préstamo"}</button></div></div></div>}
    {modal==="return"&&owned&&<div className="modal-back"><form className="return-modal" onSubmit={e=>{e.preventDefault();if(!returnRating){flash("Selecciona una calificación antes de devolver el libro");return}setOwned(null);setModal(null);setReturnRating(0);flash("Libro devuelto. ¡Gracias por dejar una huella!")}}><button type="button" className="close" onClick={()=>setModal(null)}>×</button><p className="eyebrow">ANTES DE DEVOLVERLO</p><h2>Deja una huella para quien sigue</h2><p>Tu respuesta ayudará a los próximos lectores de <b>{owned.title}</b>.</p><label>¿Qué cambió en el personaje principal?<textarea required placeholder="Escribe tu respuesta…"/></label><label>Propón una pregunta para futuros lectores<textarea required placeholder="¿Qué te gustaría preguntarles?"/></label><label>¿Cómo calificas esta lectura?<Stars rating={returnRating} onSelect={setReturnRating}/><small className="rating-help">{returnRating?`${returnRating} de 5 estrellas`:"Selecciona de 1 a 5 estrellas"}</small></label><button className="primary wide">Completar devolución</button></form></div>}
    {modal==="profile"&&<div className="modal-back" onClick={()=>setModal(null)}><form className="profile-modal" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();setModal(null);flash("Perfil actualizado")}}><button type="button" className="close" onClick={()=>setModal(null)}>×</button><Avatar name="Amelia" color="#cf915f"/><button type="button" className="photo-button">Cambiar foto</button><label>Tu nombre<input defaultValue="Amelia Rivera"/></label><label>Sobre ti<textarea defaultValue="Lectora curiosa, amante de los jardines y las historias que se quedan contigo."/></label><div className="stats"><span><b>1,426</b> páginas</span><span><b>12</b> libros</span><span><b>8</b> reflexiones</span></div><button className="primary wide">Guardar perfil</button></form></div>}
    {authView&&<div className="modal-back" onClick={()=>{setAuthView(null);setRecoverySent(false)}}><form className="auth-modal" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();if(authView==="recover"){setRecoverySent(true);return}completeAuth(authView==="signup"?"Cuenta creada correctamente":"Bienvenida de nuevo")}}><button type="button" className="close" onClick={()=>{setAuthView(null);setRecoverySent(false)}}>×</button><div className="auth-mark">B</div>{authView==="login"&&<><p className="eyebrow">ACCESO DE LECTORES</p><h2>Iniciar sesión</h2><p>Continúa con tus préstamos, lecturas y conversaciones.</p><label>Correo electrónico<input required type="email" placeholder="nombre@correo.com" autoComplete="email"/></label><label>Contraseña<input required type="password" placeholder="Tu contraseña" autoComplete="current-password"/></label><button className="forgot" type="button" onClick={()=>setAuthView("recover")}>Olvidé mi contraseña</button><button className="primary wide">Iniciar sesión</button><p className="auth-switch">¿Aún no tienes cuenta? <button type="button" onClick={()=>setAuthView("signup")}>Regístrate</button></p></>}{authView==="signup"&&<><p className="eyebrow">NUEVA CUENTA</p><h2>Crear una cuenta</h2><p>Regístrate para tomar libros y participar en la comunidad.</p><label>Nombre<input required placeholder="Tu nombre" autoComplete="name"/></label><label>Correo electrónico<input required type="email" placeholder="nombre@correo.com" autoComplete="email"/></label><label>Contraseña<input required type="password" minLength={8} placeholder="Mínimo 8 caracteres" autoComplete="new-password"/></label><label>Confirmar contraseña<input required type="password" minLength={8} placeholder="Repite tu contraseña" autoComplete="new-password"/></label><button className="primary wide">Crear cuenta</button><p className="auth-switch">¿Ya tienes cuenta? <button type="button" onClick={()=>setAuthView("login")}>Inicia sesión</button></p></>}{authView==="recover"&&<><p className="eyebrow">RECUPERAR ACCESO</p><h2>Restablecer contraseña</h2>{recoverySent?<div className="recovery-success"><b>Revisa tu correo</b><p>Si existe una cuenta asociada, recibirás un enlace para crear una nueva contraseña.</p><button type="button" className="secondary wide" onClick={()=>{setAuthView("login");setRecoverySent(false)}}>Volver a iniciar sesión</button></div>:<><p>Escribe el correo de tu cuenta y te enviaremos un enlace de recuperación.</p><label>Correo electrónico<input required type="email" placeholder="nombre@correo.com" autoComplete="email"/></label><button className="primary wide">Enviar enlace</button><p className="auth-switch"><button type="button" onClick={()=>setAuthView("login")}>← Volver a iniciar sesión</button></p></>}</>}</form></div>}
    {toast&&<div className="toast">✓ {toast}</div>}
  </main>
}
